included: # File Paths to be included
  - ProfileCreator

excluded: # File Paths to be excluded
  - ProfileCreator/Extensions/ColorKeywordMap.swift 
  - ProfileCreator/ExtensionsOld/ColorKeywordMap.swift

opt_in_rules: # Optional Rules
  - array_init
  #IGNORE - attributes
  - closure_end_indentation
  - closure_spacing
  #IGNORE - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - discouraged_optional_boolean
  #EVALUATE- discouraged_optional_collection
  - empty_count
  - empty_string
  #EVALUATE- explicit_acl
  #IGNORE- explicit_enum_raw_value
  - explicit_init
  #EVALUATE- explicit_top_level_acl
  #EVALUATE- explicit_type_interface
  #EVALUATE- extension_access_modifier
  - fatal_error_message
  - file_header
  - first_where
  #- force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  #- lower_acl_than_parent
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  #EVALUATE- no_grouping_extension
  - number_separator
  #- object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  #IGNORE- vertical_parameter_alignment_on_call
  #EVALUATE- yoda_condition
  
disabled_rules:
  - block_based_kvo
  #- class_delegate_protocol
  #- closing_brace
  #- closure_parameter_position
  #- colon
  #- comma
  #- compiler_protocol_init
  #- control_statement
  #- custom_rules
  - cyclomatic_complexity
  #- discarded_notification_center_observer
  #- discouraged_direct_init
  #- dynamic_inline
  #- empty_enum_arguments
  #- empty_parameters
  #- empty_parentheses_with_trailing_closure
  #- fallthrough
  - file_length
  #- for_where
  #- force_cast
  #- force_try
  - function_body_length
  - function_parameter_count
  #- generic_type_name
  - identifier_name
  #- implicit_getter
  #- is_disjoint
  #- large_tuple
  #- leading_whitespace
  #- legacy_cggeometry_functions
  #- legacy_constant
  #- legacy_constructor
  #- legacy_nsgeometry_functions  
  - line_length
  #- mark
  #- multiple_closures_with_trailing_closure
  #- nesting
  #- notification_center_detachment
  #- opening_brace
  #- operator_whitespace
  #- private_over_fileprivate
  #- private_unit_test
  #- protocol_property_accessors_order
  #- redundant_discardable_let
  #- redundant_optional_initialization
  #- redundant_string_enum_value
  #- redundant_void_return
  #- return_arrow_whitespace
  #- shorthand_operator
  #- statement_position
  #- superfluous_disable_command
  #- switch_case_alignment
  #- syntactic_sugar
  - todo
  #- trailing_comma
  #- trailing_newline
  #- trailing_semicolon
  #- trailing_whitespace  
  - type_body_length
  - type_name
  #- unneeded_break_in_switch
  #- unused_closure_parameter
  #- unused_enumerated
  #- unused_optional_binding
  #- valid_ibinspectable
  #- vertical_parameter_alignment
  #- vertical_whitespace
  #- void_return
  #- weak_delegate
  #- xctfail_message
  

file_header: # Correct syntax for the file headers
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  ProfileCreator
                    \/\/
                    \/\/  Created by .[A-Za-z -]*?.
                    \/\/  Copyright © \d{4} .[A-Za-z -]*?.\. All rights reserved\.
                    \/\/
